defmodule TypeSafe.Error do
  @moduledoc """
  The single exception struct returned (or raised) by every TypeSafe function.

  Match on `:type` instead of on exception modules:

      case TypeSafe.ask(client, state, questions) do
        {:ok, response} -> handle(response)
        {:error, %TypeSafe.Error{type: :rate_limited, retry_after_ms: ms}} -> schedule_retry(ms)
        {:error, %TypeSafe.Error{type: :invalid_request, details: issues}} -> log_issues(issues)
        {:error, %TypeSafe.Error{} = error} -> Logger.error(Exception.message(error))
      end

  ## Types

  | `type` | Trigger | Retried by default |
  | --- | --- | --- |
  | `:invalid_request` | The request failed client-side validation before sending (no questions, one Score level, a bad option key) | no |
  | `:bad_request` | HTTP 400, for example an unknown model | no |
  | `:authentication` | HTTP 401 | no |
  | `:permission_denied` | HTTP 403, including a missing API key header | no |
  | `:not_found` | HTTP 404 | no |
  | `:unprocessable` | HTTP 422; `body` carries the server's field details verbatim | no |
  | `:rate_limited` | HTTP 429 | yes |
  | `:overloaded` | HTTP 529 | yes |
  | `:server` | Any other 5xx | yes |
  | `:api` | Any other non-2xx status (408 is retried by the default policy) | no |
  | `:transport` | A `Req.TransportError` such as `:econnrefused` or `:closed`, or another HTTP client failure | yes |
  | `:timeout` | A `Req.TransportError` with reason `:timeout` | yes |
  | `:invalid_response` | A 2xx response whose body failed the response schema | no |

  Errors surfaced after retries describe the final attempt. The number of retries is reported
  on the `[:typesafe, :request, :stop]` telemetry event, not on this struct.

  ## Fields

    * `:type` - one of the atoms in the table above.
    * `:message` - a human-readable description of the problem.
    * `:status` - the HTTP status, or `nil` for transport, timeout and invalid request errors.
      An `:invalid_response` error carries the 2xx status of the response that failed to decode.
    * `:body` - the decoded JSON body, the raw text, or `nil` for an empty body.
    * `:headers` - the response headers as returned by Req, a map of lowercase name to values.
    * `:request_id` - the `x-typesafe-request-id` response header, when present.
    * `:endpoint` - the method and URL, such as `"POST https://api.typesafe.ai/v1/systemone"`.
    * `:retry_after_ms` - the server's requested wait in milliseconds for `:rate_limited` and
      `:overloaded` errors, from the `retry-after-ms` or `Retry-After` header.
    * `:path` - the offending field as a list of strings, for `:invalid_request` and
      `:invalid_response`, such as `["answers", "tone", "confidence"]`.
    * `:details` - the list of `Zoi.Error` structs behind an `:invalid_request` or
      `:invalid_response` error, each with its own `path`, `code` and `message`.
    * `:reason` - the underlying transport reason, such as `:timeout` or `:econnrefused`, or
      the exception that caused a `:transport` error.
  """

  alias TypeSafe.Schema

  @types [
    :invalid_request,
    :bad_request,
    :authentication,
    :permission_denied,
    :not_found,
    :unprocessable,
    :rate_limited,
    :overloaded,
    :server,
    :api,
    :transport,
    :timeout,
    :invalid_response
  ]

  @typedoc "The error category to pattern-match on."
  @type type ::
          :invalid_request
          | :bad_request
          | :authentication
          | :permission_denied
          | :not_found
          | :unprocessable
          | :rate_limited
          | :overloaded
          | :server
          | :api
          | :transport
          | :timeout
          | :invalid_response

  @type t :: %__MODULE__{
          type: type(),
          message: String.t(),
          status: pos_integer() | nil,
          body: term(),
          headers: %{optional(String.t()) => [String.t()]},
          request_id: String.t() | nil,
          endpoint: String.t() | nil,
          retry_after_ms: non_neg_integer() | nil,
          path: [String.t()] | nil,
          details: [Zoi.Error.t()] | nil,
          reason: term()
        }

  defexception type: :api,
               message: nil,
               status: nil,
               body: nil,
               headers: %{},
               request_id: nil,
               endpoint: nil,
               retry_after_ms: nil,
               path: nil,
               details: nil,
               reason: nil

  # `exception/1` is generated by `defexception`: a message string or a keyword list of fields.
  @spec exception(String.t() | keyword()) :: t()

  @max_body_in_message 200
  @request_id_header "x-typesafe-request-id"

  @doc """
  Returns every error type, in the order of the table above.

      iex> :rate_limited in TypeSafe.Error.types()
      true
  """
  @spec types() :: [type()]
  def types, do: @types

  @doc """
  Renders the error on one line: type, status, message, first validation issue, endpoint and
  request id.

      iex> error = %TypeSafe.Error{type: :rate_limited, status: 429, message: "slow down", request_id: "req_1"}
      iex> Exception.message(error)
      "rate_limited (HTTP 429): slow down [request_id: req_1]"
  """
  @impl Exception
  @spec message(t()) :: String.t()
  def message(%__MODULE__{} = error) do
    head = if error.status, do: "#{error.type} (HTTP #{error.status})", else: to_string(error.type)
    body = error.message || default_message(error.type)

    location =
      case error.path do
        [_ | _] = path -> [" at ", Enum.intersperse(path, ".")]
        _ -> []
      end

    context =
      [
        error.endpoint && "endpoint: #{error.endpoint}",
        error.request_id && "request_id: #{error.request_id}"
      ]
      |> Enum.reject(&is_nil/1)
      |> case do
        [] -> []
        parts -> [" [", Enum.intersperse(parts, ", "), "]"]
      end

    IO.iodata_to_binary([head, ": ", body, location, context])
  end

  @doc """
  Returns `true` when the default retry policy would retry this error.

  The predicate is the one `TypeSafe.Retry` uses: rate limits, overload, server errors,
  HTTP 408, transport failures and timeouts. Use it when you implement your own escalation, for
  example sending a failed case to a slower fallback.

      iex> TypeSafe.Error.retryable?(%TypeSafe.Error{type: :overloaded, status: 529})
      true
      iex> TypeSafe.Error.retryable?(%TypeSafe.Error{type: :authentication, status: 401})
      false
  """
  @spec retryable?(t(), TypeSafe.Retry.t()) :: boolean()
  def retryable?(error, policy \\ %TypeSafe.Retry{})

  def retryable?(%__MODULE__{type: type}, %TypeSafe.Retry{} = policy) when type in [:transport, :timeout],
    do: policy.retry_transport_errors

  def retryable?(%__MODULE__{status: status}, %TypeSafe.Retry{} = policy) when is_integer(status),
    do: TypeSafe.Retry.retryable_status?(policy, status)

  def retryable?(%__MODULE__{}, %TypeSafe.Retry{}), do: false

  ## Constructors (internal)

  @doc false
  @spec invalid_request(String.t(), keyword()) :: t()
  def invalid_request(message, opts \\ []), do: invalid(:invalid_request, message, Keyword.get(opts, :path, []))

  @doc false
  # A validation error that did not come from Zoi, shaped like one so `details` is always a list.
  @spec invalid(:invalid_request | :invalid_response, String.t(), [String.t()]) :: t()
  def invalid(type, message, path) when type in [:invalid_request, :invalid_response] do
    %__MODULE__{
      type: type,
      message: message,
      path: path,
      details: [%Zoi.Error{code: :custom, message: message, issue: {message, []}, path: path}]
    }
  end

  @doc false
  # Wraps Zoi validation errors once, at the boundary. `prefix` locates the validated value
  # inside the request, such as ["questions", "department"].
  @spec from_zoi([Zoi.Error.t()], atom(), [String.t()]) :: t()
  def from_zoi([_ | _] = errors, type, prefix) when type in [:invalid_request, :invalid_response] do
    # Zoi reports struct and map fields in atom-table order, which can differ between machines,
    # so issues are sorted by path to make the headline issue deterministic.
    [first | _] =
      details =
      errors
      |> Enum.map(fn error -> %{error | path: prefix ++ Schema.path(error.path)} end)
      |> Enum.sort_by(& &1.path)

    %__MODULE__{type: type, message: first.message, path: first.path, details: details}
  end

  @doc false
  @spec from_response(pos_integer(), term(), map(), String.t() | nil) :: t()
  def from_response(status, body, headers, endpoint) do
    type = type_for_status(status)

    %__MODULE__{
      type: type,
      message: message_from_body(status, body),
      status: status,
      body: body,
      headers: headers,
      request_id: request_id(headers),
      endpoint: endpoint,
      retry_after_ms: if(type in [:rate_limited, :overloaded], do: TypeSafe.Retry.parse_retry_after(headers))
    }
  end

  @doc false
  # Adds the context of the 2xx response a decoding error came from, so an `:invalid_response`
  # error carries the same status, request id, headers, decoded body and endpoint as an API
  # error.
  @spec put_response(t(), Req.Response.t(), String.t() | nil) :: t()
  def put_response(%__MODULE__{} = error, %Req.Response{} = response, endpoint) do
    %{
      error
      | status: response.status,
        request_id: request_id(response.headers),
        headers: response.headers,
        body: TypeSafe.Client.decode_body(response.body),
        endpoint: endpoint
    }
  end

  @doc false
  @spec from_exception(Exception.t(), String.t() | nil) :: t()
  def from_exception(%Req.TransportError{reason: :timeout} = exception, endpoint) do
    %__MODULE__{type: :timeout, message: Exception.message(exception), reason: :timeout, endpoint: endpoint}
  end

  def from_exception(%Req.TransportError{reason: reason} = exception, endpoint) do
    %__MODULE__{type: :transport, message: Exception.message(exception), reason: reason, endpoint: endpoint}
  end

  def from_exception(%__MODULE__{} = error, endpoint), do: %{error | endpoint: error.endpoint || endpoint}

  def from_exception(%{__exception__: true} = exception, endpoint) do
    reason = Map.get(exception, :reason, exception)
    %__MODULE__{type: :transport, message: Exception.message(exception), reason: reason, endpoint: endpoint}
  end

  @doc false
  @spec request_id(map()) :: String.t() | nil
  def request_id(headers) when is_map(headers) do
    case Map.get(headers, @request_id_header) do
      [value | _] -> value
      value when is_binary(value) -> value
      _ -> nil
    end
  end

  def request_id(_headers), do: nil

  @doc false
  @spec type_for_status(pos_integer()) ::
          :bad_request
          | :authentication
          | :permission_denied
          | :not_found
          | :unprocessable
          | :rate_limited
          | :overloaded
          | :server
          | :api
  def type_for_status(400), do: :bad_request
  def type_for_status(401), do: :authentication
  def type_for_status(403), do: :permission_denied
  def type_for_status(404), do: :not_found
  def type_for_status(422), do: :unprocessable
  def type_for_status(429), do: :rate_limited
  def type_for_status(529), do: :overloaded
  def type_for_status(status) when status in 500..599, do: :server
  def type_for_status(_status), do: :api

  # Mirrors the message extraction in TypeSafe's official Python and JavaScript SDKs,
  # plus the `{"detail": {"message": ...}}` shape the API uses for authentication and usage errors.
  defp message_from_body(status, body) do
    case {extract_message(body), body} do
      {message, _body} when is_binary(message) and message != "" ->
        message

      {_message, empty} when empty in [nil, ""] ->
        "HTTP #{status} with no body"

      _ ->
        raw = if is_binary(body), do: body, else: encode_body(body)

        if String.length(raw) > @max_body_in_message,
          do: String.slice(raw, 0, @max_body_in_message) <> "…",
          else: raw
    end
  end

  defp encode_body(body) do
    JSON.encode!(body)
  rescue
    _ -> inspect(body)
  end

  # A plain-text body has no message field; it is used as the raw body, truncated like JSON.
  defp extract_message(%{} = body) do
    Enum.find_value([body["error"], body["message"], body["detail"]], &message_from/1)
  end

  defp extract_message(_body), do: nil

  defp message_from(message) when is_binary(message) and message != "", do: message
  defp message_from(%{"message" => message}) when is_binary(message) and message != "", do: message
  defp message_from(details) when is_list(details), do: describe_validation_errors(details)
  defp message_from(_other), do: nil

  defp describe_validation_errors(details) do
    details
    |> Enum.flat_map(fn
      %{"msg" => msg} = detail when is_binary(msg) ->
        location =
          case detail["loc"] do
            loc when is_list(loc) -> loc |> Enum.reject(&(&1 == "body")) |> Enum.map_join(".", &to_string/1)
            _ -> ""
          end

        [if(location == "", do: msg, else: "#{location}: #{msg}")]

      _ ->
        []
    end)
    |> case do
      [] -> nil
      parts -> Enum.join(parts, "; ")
    end
  end

  defp default_message(:invalid_request), do: "invalid request"
  defp default_message(:invalid_response), do: "invalid response"
  defp default_message(:timeout), do: "request timed out"
  defp default_message(:transport), do: "transport error"
  defp default_message(type), do: "request failed (#{type})"
end
